"""initial_tables_reports_cache_and_usage_snapshots

Revision ID: e8fc633272b3
Revises:
Create Date: 2025-12-20 17:02:10.269808

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e8fc633272b3"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reports_cache",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "report_id", sa.Integer(), nullable=False, comment="External report ID"
        ),
        sa.Column("name", sa.String(length=255), nullable=False, comment="Report name"),
        sa.Column(
            "credit_cost",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            comment="Credit cost for this report",
        ),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.Column(
            "expires_at", sa.DateTime(), nullable=False, comment="Cache expiration time"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("report_id"),
        comment="Cache for external API report data",
    )
    op.create_index(
        "ix_reports_cache_expires", "reports_cache", ["expires_at"], unique=False
    )
    op.create_index(
        "ix_reports_cache_report_id", "reports_cache", ["report_id"], unique=False
    )
    op.create_table(
        "usage_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "snapshot_date", sa.Date(), nullable=False, comment="Date of the snapshot"
        ),
        sa.Column(
            "message_id", sa.Integer(), nullable=False, comment="External message ID"
        ),
        sa.Column(
            "timestamp", sa.DateTime(), nullable=False, comment="Message timestamp"
        ),
        sa.Column(
            "report_name",
            sa.String(length=255),
            nullable=True,
            comment="Report name if applicable",
        ),
        sa.Column(
            "credits_used",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            comment="Credits used",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        comment="Historical usage data snapshots",
    )
    op.create_index(
        "ix_usage_snapshots_date", "usage_snapshots", ["snapshot_date"], unique=False
    )
    op.create_index(
        "ix_usage_snapshots_message_id", "usage_snapshots", ["message_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_usage_snapshots_message_id", table_name="usage_snapshots")
    op.drop_index("ix_usage_snapshots_date", table_name="usage_snapshots")
    op.drop_table("usage_snapshots")
    op.drop_index("ix_reports_cache_report_id", table_name="reports_cache")
    op.drop_index("ix_reports_cache_expires", table_name="reports_cache")
    op.drop_table("reports_cache")
    # ### end Alembic commands ###
